# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e0ef43bce10b6b295a88ee2e4087c9b639d7d4440572bdd3363304f9d10412aa06ff5d0a6df35f33046d6acefd6c8514199336e140d97f112d5ad2a9acdeec

test:
  secret_key_base: 9812780c719bdaa22bc9f0b50567b896111a3ec429ce89891a53c004ae6fc38ddc4de169d6223ecc8bf104028db8e507e533ea164208fcaa46682b9fcf3e4832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
